name = "renwu-app"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "renwu-db"
database_id = "2e47a5c0-b541-461e-b998-97f359cf717d"

# R2 存储桶绑定
[[r2_buckets]]
binding = "MEDIA"
bucket_name = "renwu-media"

# Pages 构建配置
[pages_build]
build_command = ""
build_output_dir = "."